name: Run python script
on: [push]
jobs:
  run_python_script:
  runs-javascript-script:
    runs-on: ubuntu-latest
    steps:
      - name: Inicio
        run: echo "Iniciando el workflow para ejecutar el script de Python."
      - name: Clona repo
        uses: actions/checkout@v6
      - name: Ejecuta script de Python
        run: ls -al
      - name: definir variable
        run: echo "USERNAME=${{github.actor}}" >> $GITHUB_ENV
      - name: Ejecuta script de Python
        run: node app.js