name: Workflow con múltiples triggers

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Mostrar mensaje
        run: echo "El workflow se ejecutó correctamente"

      - name: Mostrar fecha
        run: date